# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatePrecinctVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyniki_2017.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('num', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('num', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('num', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=64)),
                ('allowed', models.PositiveIntegerField()),
                ('cards_issued', models.PositiveIntegerField()),
                ('invalid_votes', models.PositiveIntegerField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyniki_2017.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('num', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='voivodeship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyniki_2017.Voivodeship'),
        ),
        migrations.AddField(
            model_name='commune',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyniki_2017.District'),
        ),
        migrations.AddField(
            model_name='candidateprecinctvotes',
            name='precinct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyniki_2017.Precinct'),
        ),
    ]
