# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki_2017', '0002_auto_20170420_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='precinct',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='precinct',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
