# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki_2017', '0004_auto_20170608_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wyniki_2017.District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='voivodeship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wyniki_2017.Voivodeship'),
        ),
        migrations.AlterField(
            model_name='precinct',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wyniki_2017.Commune'),
        ),
    ]
